/* Autovinci — Centralized Mock Data */

import type {
  Vehicle,
  Lead,
  ShowroomSlide,
  OwnedCar,
  ChatMessage,
  TimelineMessage,
  Activity,
} from "./types";
import {
  CRETA,
  SWIFT,
  NEXON,
  NEXON_EV,
  XUV700,
  FORTUNER,
  SEDAN,
  KIA,
  BREZZA,
  INTERIOR,
  resizeUrl,
} from "./car-images";

// ── Vehicles ──

export const VEHICLES: Vehicle[] = [
  {
    id: "creta-sxo-2023",
    name: "Hyundai Creta SX(O)",
    year: 2023,
    price: "\u20B9 12.50 Lakh",
    priceNumeric: 1250000,
    image: CRETA,
    status: "available",
    statusColor: "bg-emerald-500",
    aiTag: true,
    aiScore: 96,
    km: "18,300",
    fuel: "Diesel",
    transmission: "Automatic",
    engine: "1.5L CRDi",
    power: "115 bhp",
    mileage: "21.4 km/l",
    location: "Delhi NCR",
    owner: "1st Owner",
    badge: "Premium",
    category: "suv",
    features: [
      { key: "sunroof", label: "Sunroof", available: true },
      { key: "adas", label: "ADAS Safety", available: true },
      { key: "ventilatedSeats", label: "Ventilated Seats", available: true },
      { key: "wirelessCharging", label: "Wireless Charging", available: true },
      { key: "cruiseControl", label: "Cruise Control", available: true },
      { key: "airPurifier", label: "Air Purifier", available: false },
    ],
    gallery: [CRETA, INTERIOR],
    panoramaImageIdx: null,
  },
  {
    id: "swift-zxi-2023",
    name: "Maruti Swift ZXi+",
    year: 2023,
    price: "\u20B9 6.80 Lakh",
    priceNumeric: 680000,
    image: SWIFT,
    status: "available",
    statusColor: "bg-emerald-500",
    aiTag: true,
    aiScore: 92,
    km: "12,500",
    fuel: "Petrol",
    transmission: "Manual",
    engine: "1.2L Dualjet",
    power: "90 bhp",
    mileage: "24.8 km/l",
    location: "Mumbai",
    owner: "1st Owner",
    badge: "Trending",
    category: "hatchback",
    features: [
      { key: "sunroof", label: "Sunroof", available: false },
      { key: "adas", label: "ADAS Safety", available: false },
      { key: "ventilatedSeats", label: "Ventilated Seats", available: false },
      { key: "wirelessCharging", label: "Wireless Charging", available: true },
      { key: "cruiseControl", label: "Cruise Control", available: true },
      { key: "airPurifier", label: "Air Purifier", available: false },
    ],
    gallery: [SWIFT, INTERIOR],
    panoramaImageIdx: null,
  },
  {
    id: "nexon-xza-2022",
    name: "Tata Nexon XZA+",
    year: 2022,
    price: "\u20B9 10.20 Lakh",
    priceNumeric: 1020000,
    image: NEXON,
    status: "in_review",
    statusColor: "bg-amber-500",
    aiTag: false,
    aiScore: 89,
    km: "22,000",
    fuel: "Petrol",
    transmission: "Automatic",
    engine: "1.2L Turbo",
    power: "120 bhp",
    mileage: "17.4 km/l",
    location: "Pune",
    owner: "1st Owner",
    badge: null,
    category: "suv",
    features: [
      { key: "sunroof", label: "Sunroof", available: true },
      { key: "adas", label: "ADAS Safety", available: false },
      { key: "ventilatedSeats", label: "Ventilated Seats", available: false },
      { key: "wirelessCharging", label: "Wireless Charging", available: true },
      { key: "cruiseControl", label: "Cruise Control", available: true },
      { key: "airPurifier", label: "Air Purifier", available: true },
    ],
    gallery: [NEXON, INTERIOR],
    panoramaImageIdx: null,
  },
  {
    id: "xuv700-ax7l-2023",
    name: "Mahindra XUV700 AX7L",
    year: 2023,
    price: "\u20B9 18.90 Lakh",
    priceNumeric: 1890000,
    image: XUV700,
    status: "available",
    statusColor: "bg-emerald-500",
    aiTag: true,
    aiScore: 94,
    km: "15,200",
    fuel: "Diesel",
    transmission: "Automatic",
    engine: "2.2L mHawk",
    power: "185 bhp",
    mileage: "16.3 km/l",
    location: "Bangalore",
    owner: "1st Owner",
    badge: "Premium",
    category: "suv",
    features: [
      { key: "sunroof", label: "Sunroof", available: true },
      { key: "adas", label: "ADAS Safety", available: true },
      { key: "ventilatedSeats", label: "Ventilated Seats", available: true },
      { key: "wirelessCharging", label: "Wireless Charging", available: true },
      { key: "cruiseControl", label: "Cruise Control", available: true },
      { key: "airPurifier", label: "Air Purifier", available: true },
    ],
    gallery: [XUV700, INTERIOR],
    panoramaImageIdx: null,
  },
  {
    id: "fortuner-legender-2021",
    name: "Toyota Fortuner Legender",
    year: 2021,
    price: "\u20B9 32.50 Lakh",
    priceNumeric: 3250000,
    image: FORTUNER,
    status: "available",
    statusColor: "bg-emerald-500",
    aiTag: true,
    aiScore: 97,
    km: "28,400",
    fuel: "Diesel",
    transmission: "Automatic",
    engine: "2.8L GD",
    power: "204 bhp",
    mileage: "14.2 km/l",
    location: "Delhi NCR",
    owner: "1st Owner",
    badge: "Premium",
    category: "suv",
    features: [
      { key: "sunroof", label: "Sunroof", available: true },
      { key: "adas", label: "ADAS Safety", available: false },
      { key: "ventilatedSeats", label: "Ventilated Seats", available: true },
      { key: "wirelessCharging", label: "Wireless Charging", available: false },
      { key: "cruiseControl", label: "Cruise Control", available: true },
      { key: "airPurifier", label: "Air Purifier", available: false },
    ],
    gallery: [FORTUNER, INTERIOR],
    panoramaImageIdx: null,
  },
  {
    id: "honda-city-2023",
    name: "Honda City ZX CVT",
    year: 2023,
    price: "\u20B9 14.20 Lakh",
    priceNumeric: 1420000,
    image: SEDAN,
    status: "available",
    statusColor: "bg-emerald-500",
    aiTag: true,
    aiScore: 93,
    km: "9,800",
    fuel: "Petrol",
    transmission: "CVT",
    engine: "1.5L i-VTEC",
    power: "121 bhp",
    mileage: "18.4 km/l",
    location: "Hyderabad",
    owner: "1st Owner",
    badge: "Low KM",
    category: "sedan",
    features: [
      { key: "sunroof", label: "Sunroof", available: true },
      { key: "adas", label: "ADAS Safety", available: true },
      { key: "ventilatedSeats", label: "Ventilated Seats", available: false },
      { key: "wirelessCharging", label: "Wireless Charging", available: true },
      { key: "cruiseControl", label: "Cruise Control", available: true },
      { key: "airPurifier", label: "Air Purifier", available: false },
    ],
    gallery: [SEDAN, INTERIOR],
    panoramaImageIdx: null,
  },
  {
    id: "kia-seltos-2024",
    name: "Kia Seltos HTX+",
    year: 2024,
    price: "\u20B9 15.60 Lakh",
    priceNumeric: 1560000,
    image: KIA,
    status: "available",
    statusColor: "bg-emerald-500",
    aiTag: true,
    aiScore: 95,
    km: "5,200",
    fuel: "Diesel",
    transmission: "Automatic",
    engine: "1.5L CRDi",
    power: "115 bhp",
    mileage: "20.7 km/l",
    location: "Chennai",
    owner: "1st Owner",
    badge: "New Arrival",
    category: "suv",
    features: [
      { key: "sunroof", label: "Sunroof", available: true },
      { key: "adas", label: "ADAS Safety", available: true },
      { key: "ventilatedSeats", label: "Ventilated Seats", available: true },
      { key: "wirelessCharging", label: "Wireless Charging", available: true },
      { key: "cruiseControl", label: "Cruise Control", available: true },
      { key: "airPurifier", label: "Air Purifier", available: true },
    ],
    gallery: [KIA, INTERIOR],
    panoramaImageIdx: null,
  },
  {
    id: "nexon-ev-2023",
    name: "Tata Nexon EV Max LR",
    year: 2023,
    price: "\u20B9 17.50 Lakh",
    priceNumeric: 1750000,
    image: NEXON_EV,
    status: "available",
    statusColor: "bg-emerald-500",
    aiTag: true,
    aiScore: 91,
    km: "11,300",
    fuel: "Electric",
    transmission: "Automatic",
    engine: "40.5 kWh",
    power: "143 bhp",
    mileage: "437 km range",
    location: "Delhi NCR",
    owner: "1st Owner",
    badge: "EV",
    category: "ev",
    features: [
      { key: "sunroof", label: "Sunroof", available: true },
      { key: "adas", label: "ADAS Safety", available: false },
      { key: "ventilatedSeats", label: "Ventilated Seats", available: true },
      { key: "wirelessCharging", label: "Wireless Charging", available: true },
      { key: "cruiseControl", label: "Cruise Control", available: true },
      { key: "airPurifier", label: "Air Purifier", available: true },
    ],
    gallery: [NEXON_EV, INTERIOR],
    panoramaImageIdx: null,
  },
  {
    id: "brezza-zxi-2022",
    name: "Maruti Brezza ZXi+",
    year: 2022,
    price: "\u20B9 11.20 Lakh",
    priceNumeric: 1120000,
    image: BREZZA,
    status: "available",
    statusColor: "bg-emerald-500",
    aiTag: true,
    aiScore: 90,
    km: "19,700",
    fuel: "Petrol",
    transmission: "Automatic",
    engine: "1.5L K-Series",
    power: "103 bhp",
    mileage: "19.8 km/l",
    location: "Jaipur",
    owner: "1st Owner",
    badge: null,
    category: "suv",
    features: [
      { key: "sunroof", label: "Sunroof", available: true },
      { key: "adas", label: "ADAS Safety", available: false },
      { key: "ventilatedSeats", label: "Ventilated Seats", available: false },
      { key: "wirelessCharging", label: "Wireless Charging", available: true },
      { key: "cruiseControl", label: "Cruise Control", available: true },
      { key: "airPurifier", label: "Air Purifier", available: false },
    ],
    gallery: [BREZZA, INTERIOR],
    panoramaImageIdx: null,
  },
];

// ── Leads ──

export const LEADS: Lead[] = [
  {
    id: "lead-1",
    name: "Amit Verma",
    source: "WEBSITE LEAD",
    sourceColor: "bg-primary text-white",
    sentiment: 94,
    sentimentLabel: "hot",
    car: "2023 Hyundai Creta SX(O)",
    carImage: CRETA,
    time: "2 hrs ago",
    message:
      "Interested in booking a test drive at my home. Budget is \u20B913L max.",
    phone: "+91 98765 43210",
    location: "Delhi",
    budget: "\u20B913L max",
  },
  {
    id: "lead-2",
    name: "Neha Gupta",
    source: "FACEBOOK MARKETPLACE",
    sourceColor: "bg-blue-600 text-white",
    sentiment: 62,
    sentimentLabel: "warm",
    car: "2022 Maruti Swift ZXi+",
    carImage: SWIFT,
    time: "5 hrs ago",
    message:
      "Asking about insurance transfer and RC status for the Swift.",
    phone: "+91 91234 56789",
    location: "Mumbai",
    budget: "\u20B98L max",
  },
  {
    id: "lead-3",
    name: "Ravi Malhotra",
    source: "WEBSITE LEAD",
    sourceColor: "bg-primary text-white",
    sentiment: 88,
    sentimentLabel: "hot",
    car: "2021 Tata Nexon XZA+",
    carImage: NEXON,
    time: "1 day ago",
    message:
      "Wants home delivery to Noida. Ready to finalize within the week.",
    phone: "+91 99876 54321",
    location: "Noida",
    budget: "\u20B912L max",
  },
  {
    id: "lead-4",
    name: "Priya Sharma",
    source: "INSTAGRAM DM",
    sourceColor: "bg-pink-600 text-white",
    sentiment: 45,
    sentimentLabel: "cool",
    car: "2023 Honda City ZX CVT",
    carImage: SEDAN,
    time: "2 days ago",
    message: "Just browsing options for now. Will visit next month.",
    phone: "+91 88765 43210",
    location: "Bangalore",
    budget: "\u20B915L max",
  },
];

// ── Lead Detail Timeline ──

export const LEAD_TIMELINE: TimelineMessage[] = [
  {
    id: 1,
    role: "ai",
    text: "AI auto-replied with test drive options for this Saturday.",
    time: "2h ago",
    type: "auto",
  },
  {
    id: 2,
    role: "user",
    text: "Thanks! I\u2019ll take the 11 AM slot. Can you send the address?",
    time: "1h ago",
    type: "manual",
  },
  {
    id: 3,
    role: "ai",
    text: "Sure! Sending location. Your test drive is confirmed for 11 AM at Malhotra Auto, Dwarka.",
    time: "58m ago",
    type: "manual",
  },
  {
    id: 4,
    role: "user",
    text: "Perfect. One more thing \u2014 what\u2019s the final on-road price with insurance?",
    time: "45m ago",
    type: "manual",
  },
];

// ── Concierge Chat ──

export const INITIAL_CHAT_MESSAGES: ChatMessage[] = [
  {
    id: 1,
    role: "ai",
    text: "Welcome to Autovinci Concierge. I\u2019m your AI-powered car buying assistant. I can help you find the perfect car, check inspection reports, calculate EMIs, or schedule test drives. How can I help you today?",
  },
  {
    id: 2,
    role: "user",
    text: "I\u2019m looking for a reliable SUV under \u20B915 Lakhs in Delhi. Something family-friendly with good mileage.",
  },
  {
    id: 3,
    role: "ai",
    text: "Excellent choice! I\u2019ve found 8 AI-verified SUVs under \u20B915 Lakhs in Delhi NCR. Here\u2019s my top recommendation based on your criteria:",
    car: {
      name: "2023 Hyundai Creta SX(O)",
      price: "\u20B912.50 Lakh",
      specs: "18,300 km \u2022 Diesel \u2022 Automatic",
      image: CRETA,
    },
  },
];

// ── Showroom Slides ──

export const SHOWROOM_SLIDES: ShowroomSlide[] = [
  {
    id: "slide-1",
    name: "The Visionary",
    subtitle: "Redefining Automotive Excellence",
    edition: "Limited Edition",
    image: resizeUrl(CRETA, 1200),
    desc: "2023 Hyundai Creta SX(O) \u2014 Hand-inspected, AI-certified. The most sought-after SUV in India\u2019s premium used car market.",
  },
  {
    id: "slide-2",
    name: "The Maverick",
    subtitle: "Born to Command the Road",
    edition: "Exclusive Collection",
    image: resizeUrl(XUV700, 1200),
    desc: "2023 Mahindra XUV700 AX7L \u2014 A powerhouse of technology and comfort. AI health score: 97/100. Zero compromises.",
  },
  {
    id: "slide-3",
    name: "The Timeless",
    subtitle: "Heritage Meets Innovation",
    edition: "Signature Series",
    image: resizeUrl(FORTUNER, 1200),
    desc: "2021 Toyota Fortuner Legender \u2014 A legacy of reliability, now AI-enhanced with 360\u00B0 virtual tour and complete service history.",
  },
];

// ── Dashboard Activities ──

export const DASHBOARD_ACTIVITIES: Activity[] = [
  {
    title: "Social Post Generated",
    desc: "Auto-captions for Maruti Swift ready for Instagram & FB.",
    time: "2m ago",
    type: "auto",
  },
  {
    title: "360\u00B0 View Processed",
    desc: "Hyundai Creta interior panorama successfully stitched.",
    time: "1h ago",
    type: "info",
  },
  {
    title: "New Lead: Amit Verma",
    desc: "Interested in Creta SX(O). Budget \u20B913L. AI auto-replied.",
    time: "2h ago",
    type: "success",
  },
];

// ── Owned Car (My Cars) ──

export const MY_CAR: OwnedCar = {
  id: "owned-creta",
  name: "2023 Hyundai Creta SX(O)",
  vin: "MALA51CF1KH000001",
  image: CRETA,
  purchaseDate: "15 Jan 2026",
  warranty: "Valid until Jan 2028",
  nextService: "28 Feb 2026",
  insurance: "Expires 14 Jan 2027",
  km: "21,400",
};

// ── Helper: get vehicle by ID ──

export function getVehicleById(id: string): Vehicle | undefined {
  return VEHICLES.find((v) => v.id === id);
}

// ── Comparison Specs ──

export const COMPARISON_SPECS = [
  { key: "km", label: "Kilometers" },
  { key: "fuel", label: "Fuel Type" },
  { key: "transmission", label: "Transmission" },
  { key: "engine", label: "Engine" },
  { key: "power", label: "Power" },
  { key: "mileage", label: "Mileage" },
  { key: "aiScore", label: "AI Health Score" },
] as const;
