"use client";

import Image from "next/image";
import Link from "next/link";
import { MaterialIcon } from "@/components/MaterialIcon";
import { CRETA, SWIFT, NEXON, BLUR_DATA_URL } from "@/lib/car-images";

/* ── design tokens: ai_performance_analytics_(dark) ── */
// primary: #137fec, accent-cyan: #00f2ff, font: Inter, bg: #0b0e14, card: #161b22

const GAUGES = [
  { label: "Task Completion", value: "92%", offset: 8, color: "#137fec" },
  { label: "Lead Conversion", value: "+18%", offset: 40, color: "#00f2ff" },
  { label: "Time Saved", value: "140h", offset: 20, color: "#a855f7" },
];

const BAR_DAYS = [
  { day: "Mon", organic: 8, boosted: 20 },
  { day: "Tue", organic: 10, boosted: 14 },
  { day: "Wed", organic: 6, boosted: 24 },
  { day: "Thu", organic: 14, boosted: 18 },
  { day: "Fri", organic: 4, boosted: 28 },
];

const TOP_POSTS = [
  { name: "2023 Hyundai Creta SX(O)", img: CRETA, likes: "4.2k", shares: "1.8k", views: "12k", conv: "+18%" },
  { name: "2022 Maruti Swift ZXi+", img: SWIFT, likes: "3.8k", shares: "920", views: "8.4k", conv: "+12%" },
  { name: "2021 Tata Nexon XZA+", img: NEXON, likes: "5.1k", shares: "2.4k", views: "15k", conv: "+24%" },
];

export default function PerformancePage() {
  return (
    <div
      className="min-h-screen max-w-md mx-auto flex flex-col pb-24"
      style={{ fontFamily: "'Inter', sans-serif", background: "#0b0e14", color: "#e2e8f0" }}
    >
      {/* ── Header ── */}
      <header
        className="flex items-center justify-between px-6 py-4 sticky top-0 z-50 border-b"
        style={{
          background: "rgba(11,14,20,0.8)",
          backdropFilter: "blur(12px)",
          borderColor: "rgba(255,255,255,0.05)",
        }}
      >
        <div className="flex items-center gap-3">
          <div
            className="w-10 h-10 rounded-lg flex items-center justify-center border"
            style={{ background: "rgba(19,127,236,0.2)", borderColor: "rgba(19,127,236,0.3)" }}
          >
            <MaterialIcon name="analytics" className="text-[#137fec]" />
          </div>
          <h1 className="text-xl font-bold tracking-tight text-white">AI Analytics</h1>
        </div>
        <div className="flex items-center gap-4">
          <button className="relative p-2 text-slate-400">
            <MaterialIcon name="notifications" />
            <span
              className="absolute top-2 right-2 w-2 h-2 rounded-full border-2"
              style={{ background: "#137fec", borderColor: "#0b0e14" }}
            />
          </button>
          <div
            className="w-8 h-8 rounded-full border flex items-center justify-center text-xs font-bold text-white"
            style={{ background: "#334155", borderColor: "rgba(255,255,255,0.1)" }}
          >
            R
          </div>
        </div>
      </header>

      <main className="flex-1 overflow-y-auto px-4 pb-4">
        {/* ── Hero ROI Card ── */}
        <section className="mt-6">
          <div
            className="rounded-xl p-6 relative overflow-hidden"
            style={{
              background: "rgba(22,27,34,0.8)",
              backdropFilter: "blur(12px)",
              border: "1px solid rgba(255,255,255,0.05)",
              boxShadow: "0 0 15px rgba(19,127,236,0.3)",
            }}
          >
            <div className="relative z-10">
              <p className="text-xs font-semibold uppercase tracking-widest" style={{ color: "#137fec" }}>
                Total ROI
              </p>
              <div className="flex items-end gap-3 mt-1">
                <h2 className="text-4xl font-bold tracking-tight text-white">₹42.5L</h2>
                <span className="mb-1 text-emerald-400 font-medium text-sm flex items-center">
                  <MaterialIcon name="trending_up" className="text-sm mr-1" />
                  +12.4%
                </span>
              </div>
              <p className="text-slate-400 text-sm mt-1 italic font-light">
                Generated by AI automation
              </p>
            </div>
            {/* Mini trend bg */}
            <svg
              className="absolute bottom-0 right-0 w-full h-24 opacity-20 pointer-events-none"
              preserveAspectRatio="none"
              viewBox="0 0 400 100"
            >
              <defs>
                <linearGradient id="roiGrad" x1="0%" y1="0%" x2="0%" y2="100%">
                  <stop offset="0%" stopColor="#137fec" stopOpacity="1" />
                  <stop offset="100%" stopColor="transparent" stopOpacity="0" />
                </linearGradient>
              </defs>
              <path
                d="M0,80 Q50,70 100,85 T200,50 T300,30 T400,10 L400,100 L0,100 Z"
                fill="url(#roiGrad)"
              />
            </svg>
          </div>
        </section>

        {/* ── Gauge Metrics ── */}
        <section className="mt-8">
          <h3 className="text-sm font-semibold text-slate-500 uppercase tracking-widest px-1 mb-4">
            AI Efficiency Metrics
          </h3>
          <div className="flex items-center justify-between gap-3">
            {GAUGES.map((g) => (
              <div
                key={g.label}
                className="flex flex-col items-center gap-3 rounded-xl p-4 flex-1"
                style={{
                  background: "rgba(22,27,34,0.8)",
                  backdropFilter: "blur(12px)",
                  border: "1px solid rgba(255,255,255,0.05)",
                }}
              >
                <div className="relative w-16 h-16">
                  <svg className="w-full h-full" viewBox="0 0 36 36">
                    <circle
                      cx="18" cy="18" r="16"
                      fill="none" strokeWidth="3"
                      stroke="#1e293b"
                    />
                    <circle
                      cx="18" cy="18" r="16"
                      fill="none" strokeWidth="3"
                      stroke={g.color}
                      strokeDasharray="100"
                      strokeDashoffset={g.offset}
                      strokeLinecap="round"
                    />
                  </svg>
                  <div className="absolute inset-0 flex items-center justify-center">
                    <span className="text-xs font-bold text-white">{g.value}</span>
                  </div>
                </div>
                <p className="text-[10px] text-center font-medium leading-tight text-slate-400">
                  {g.label}
                </p>
              </div>
            ))}
          </div>
        </section>

        {/* ── Social Reach Bar Chart ── */}
        <section className="mt-8">
          <div
            className="rounded-xl p-6"
            style={{
              background: "rgba(22,27,34,0.8)",
              backdropFilter: "blur(12px)",
              border: "1px solid rgba(255,255,255,0.05)",
            }}
          >
            <div className="flex items-center justify-between mb-6">
              <div>
                <h3 className="font-bold text-lg text-white">Social Reach</h3>
                <p className="text-xs text-slate-400">Comparing Organic vs AI Boost</p>
              </div>
              <MaterialIcon name="more_horiz" className="text-slate-500" />
            </div>
            <div className="flex items-end gap-4 h-40 w-full px-2">
              {BAR_DAYS.map((d) => (
                <div key={d.day} className="flex-1 flex flex-col justify-end gap-0.5">
                  <div
                    className="w-full rounded-t-sm"
                    style={{ height: `${d.organic * 4}px`, background: "rgba(19,127,236,0.4)" }}
                  />
                  <div
                    className="w-full rounded-b-sm"
                    style={{ height: `${d.boosted * 4}px`, background: "#137fec" }}
                  />
                  <span className="text-[10px] text-center text-slate-500 mt-2">{d.day}</span>
                </div>
              ))}
            </div>
            <div className="flex items-center gap-6 mt-6 pt-4 border-t" style={{ borderColor: "rgba(255,255,255,0.05)" }}>
              <div className="flex items-center gap-2">
                <span className="w-2 h-2 rounded-full" style={{ background: "rgba(19,127,236,0.4)" }} />
                <span className="text-xs text-slate-400">Organic</span>
              </div>
              <div className="flex items-center gap-2">
                <span className="w-2 h-2 rounded-full" style={{ background: "#137fec" }} />
                <span className="text-xs text-slate-400">AI Boosted</span>
              </div>
            </div>
          </div>
        </section>

        {/* ── Top Performing AI Posts ── */}
        <section className="mt-8 mb-4">
          <h3 className="text-sm font-semibold text-slate-500 uppercase tracking-widest px-1 mb-4">
            Top Performing AI Posts
          </h3>
          <div className="space-y-3">
            {TOP_POSTS.map((p) => (
              <div
                key={p.name}
                className="rounded-xl p-3 flex items-center gap-4"
                style={{
                  background: "rgba(22,27,34,0.8)",
                  backdropFilter: "blur(12px)",
                  border: "1px solid rgba(255,255,255,0.05)",
                }}
              >
                <div className="w-16 h-16 rounded-lg overflow-hidden shrink-0 border" style={{ borderColor: "rgba(255,255,255,0.1)" }}>
                  <Image src={p.img} alt="" width={64} height={64} className="w-full h-full object-cover" placeholder="blur" blurDataURL={BLUR_DATA_URL} />
                </div>
                <div className="flex-1 min-w-0">
                  <h4 className="font-semibold text-sm text-white truncate">{p.name}</h4>
                  <div className="flex items-center gap-4 mt-2">
                    <div className="flex items-center gap-1">
                      <MaterialIcon name="favorite" className="!text-[16px] text-rose-500" />
                      <span className="text-xs text-slate-400">{p.likes}</span>
                    </div>
                    <div className="flex items-center gap-1">
                      <MaterialIcon name="share" className="!text-[16px] text-[#137fec]" />
                      <span className="text-xs text-slate-400">{p.shares}</span>
                    </div>
                    <div className="flex items-center gap-1">
                      <MaterialIcon name="visibility" className="!text-[16px] text-[#00f2ff]" />
                      <span className="text-xs text-slate-400">{p.views}</span>
                    </div>
                  </div>
                </div>
                <div className="text-right shrink-0">
                  <p className="text-emerald-400 text-xs font-bold">{p.conv}</p>
                  <p className="text-[10px] text-slate-500">Conversion</p>
                </div>
              </div>
            ))}
          </div>
        </section>
      </main>

      {/* ── Bottom Nav ── */}
      <nav
        className="fixed bottom-0 left-0 right-0 max-w-md mx-auto z-50 px-4 pb-6 pt-3 border-t"
        style={{
          background: "rgba(11,14,20,0.9)",
          backdropFilter: "blur(16px)",
          borderColor: "rgba(255,255,255,0.05)",
        }}
      >
        <div className="flex items-center justify-around max-w-md mx-auto">
          {[
            { icon: "directions_car", label: "Inventory", href: "/inventory" },
            { icon: "campaign", label: "Marketing", href: "/social-hub" },
            { icon: "bar_chart", label: "Analytics", href: "/performance", active: true },
            { icon: "settings", label: "Settings", href: "/settings" },
          ].map((item) => (
            <Link
              key={item.label}
              href={item.href}
              className={`flex flex-col items-center gap-1 ${
                item.active ? "text-[#137fec]" : "text-slate-500"
              }`}
            >
              <div className="relative">
                <MaterialIcon name={item.icon} fill={item.active} />
                {item.active && (
                  <span className="absolute -top-1 -right-1 w-1.5 h-1.5 rounded-full" style={{ background: "#137fec" }} />
                )}
              </div>
              <span className={`text-[10px] uppercase tracking-tight ${item.active ? "font-bold" : "font-medium"}`}>
                {item.label}
              </span>
            </Link>
          ))}
        </div>
      </nav>
    </div>
  );
}
