"use client";

import Link from "next/link";
import { MaterialIcon } from "@/components/MaterialIcon";

/* Stitch: luxury_dealer_dashboard — #0dccf2, Manrope, #0a0f0f */

const HEATMAP_CITIES = [
  { city: "Mumbai", heat: 95, color: "#ef4444" },
  { city: "Delhi", heat: 88, color: "#f97316" },
  { city: "Bangalore", heat: 76, color: "#eab308" },
  { city: "Chennai", heat: 62, color: "#22c55e" },
  { city: "Hyderabad", heat: 71, color: "#eab308" },
  { city: "Pune", heat: 58, color: "#22c55e" },
];

const SOCIAL = [
  { platform: "Instagram", count: "12.4K", icon: "photo_camera", color: "#e1306c" },
  { platform: "Facebook", count: "8.2K", icon: "thumb_up", color: "#1877f2" },
  { platform: "WhatsApp", count: "3.1K", icon: "chat", color: "#25d366" },
];

const ALERTS = [
  { title: "VIP client inquiry — Creta Knight", desc: "Rajesh M. from Mumbai requests private viewing", badge: "URGENT", badgeColor: "#ef4444", time: "2 min ago" },
  { title: "Price alert triggered", desc: "Nexon EV dropped below target acquisition price", badge: "ACTION", badgeColor: "#f97316", time: "1 hr ago" },
  { title: "Monthly report ready", desc: "January 2026 performance report generated by AI", badge: "INFO", badgeColor: "#0dccf2", time: "3 hrs ago" },
];

export default function DashboardLuxuryPage() {
  return (
    <div
      className="min-h-dvh w-full flex flex-col max-w-md mx-auto text-slate-100 pb-24"
      style={{ fontFamily: "'Manrope', sans-serif", background: "#0a0f0f" }}
    >
      {/* Header */}
      <header className="sticky top-0 z-30 px-4 py-4 flex items-center justify-between border-b"
        style={{ background: "rgba(10,15,15,0.8)", backdropFilter: "blur(12px)", borderColor: "rgba(13,204,242,0.1)" }}>
        <div className="flex items-center gap-3">
          <div className="size-10 rounded-full border-2 border-[#0dccf2]/30 flex items-center justify-center bg-[#0dccf2]/10 text-[#0dccf2] font-bold text-sm">AV</div>
          <div>
            <p className="text-[10px] uppercase tracking-widest text-[#0dccf2] font-bold">Elite Dashboard</p>
            <h1 className="text-lg font-bold">Sterling Motors</h1>
          </div>
        </div>
        <div className="flex gap-2">
          <button className="size-10 rounded-full bg-white/5 flex items-center justify-center text-slate-400">
            <MaterialIcon name="notifications" />
          </button>
        </div>
      </header>

      <main className="flex-1 overflow-y-auto px-4 pb-8">
        {/* Revenue Stat */}
        <section className="py-6">
          <div className="rounded-2xl p-6 relative overflow-hidden"
            style={{ background: "linear-gradient(145deg, rgba(13,204,242,0.1) 0%, rgba(10,15,15,1) 100%)", border: "1px solid rgba(13,204,242,0.15)" }}>
            <div className="absolute top-0 left-0 w-full h-1" style={{ background: "linear-gradient(to right, transparent, #0dccf2, transparent)" }} />
            <p className="text-[10px] uppercase tracking-widest text-slate-500 mb-1">Revenue This Month</p>
            <p className="text-4xl font-bold text-white">₹1.2<span className="text-xl text-slate-400">Cr</span></p>
            <div className="flex items-center gap-1 mt-2">
              <MaterialIcon name="trending_up" className="text-sm text-[#10b981]" />
              <span className="text-xs font-bold text-[#10b981]">+24% vs last month</span>
            </div>
          </div>
        </section>

        {/* Demand Heatmap */}
        <section className="mb-6">
          <h2 className="text-xs font-bold uppercase tracking-widest text-slate-500 mb-3 flex items-center gap-2">
            <MaterialIcon name="map" className="text-sm text-[#0dccf2]" /> Demand Heatmap
          </h2>
          <div className="rounded-xl p-4" style={{ background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.05)" }}>
            <div className="grid grid-cols-3 gap-3">
              {HEATMAP_CITIES.map((c) => (
                <div key={c.city} className="rounded-lg p-3 text-center" style={{ background: "rgba(255,255,255,0.03)" }}>
                  <div className="size-10 rounded-full mx-auto mb-2 flex items-center justify-center" style={{ background: `${c.color}20`, border: `2px solid ${c.color}40` }}>
                    <span className="text-xs font-bold" style={{ color: c.color }}>{c.heat}</span>
                  </div>
                  <p className="text-[10px] font-bold text-slate-400 uppercase">{c.city}</p>
                </div>
              ))}
            </div>
            <div className="flex items-center justify-center gap-4 mt-4">
              <div className="flex items-center gap-1"><div className="size-2 rounded-full bg-[#22c55e]" /><span className="text-[10px] text-slate-500">Low</span></div>
              <div className="flex items-center gap-1"><div className="size-2 rounded-full bg-[#eab308]" /><span className="text-[10px] text-slate-500">Medium</span></div>
              <div className="flex items-center gap-1"><div className="size-2 rounded-full bg-[#ef4444]" /><span className="text-[10px] text-slate-500">High</span></div>
            </div>
          </div>
        </section>

        {/* Social Impressions */}
        <section className="mb-6">
          <h2 className="text-xs font-bold uppercase tracking-widest text-slate-500 mb-3">Social Impressions</h2>
          <div className="grid grid-cols-3 gap-3">
            {SOCIAL.map((s) => (
              <div key={s.platform} className="rounded-xl p-4 text-center"
                style={{ background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.05)" }}>
                <MaterialIcon name={s.icon} className="text-2xl mb-2" style={{ color: s.color }} />
                <p className="text-lg font-bold text-white">{s.count}</p>
                <p className="text-[10px] text-slate-500 uppercase">{s.platform}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Elite Alerts */}
        <section>
          <h2 className="text-xs font-bold uppercase tracking-widest text-slate-500 mb-3">Elite Alerts</h2>
          <div className="space-y-3">
            {ALERTS.map((a) => (
              <div key={a.title} className="rounded-xl p-4 flex items-start gap-3"
                style={{ background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.05)" }}>
                <div className="flex-1">
                  <div className="flex items-center gap-2 mb-1">
                    <h3 className="text-sm font-bold text-white">{a.title}</h3>
                    <span className="text-[8px] font-bold uppercase px-1.5 py-0.5 rounded" style={{ background: `${a.badgeColor}20`, color: a.badgeColor }}>{a.badge}</span>
                  </div>
                  <p className="text-xs text-slate-400">{a.desc}</p>
                  <p className="text-[10px] text-slate-600 mt-1">{a.time}</p>
                </div>
                <MaterialIcon name="chevron_right" className="text-slate-600 mt-1" />
              </div>
            ))}
          </div>
        </section>
      </main>

      {/* Bottom Nav */}
      <nav className="fixed bottom-0 left-0 right-0 max-w-md mx-auto z-50 border-t px-6 pb-6 pt-3 flex justify-between items-center"
        style={{ background: "rgba(10,15,15,0.95)", backdropFilter: "blur(16px)", borderColor: "rgba(255,255,255,0.05)" }}>
        <Link href="/dashboard" className="flex flex-col items-center gap-1 text-[#0dccf2]">
          <MaterialIcon name="dashboard" fill className="text-2xl" />
          <span className="text-[10px] font-bold uppercase">Dashboard</span>
        </Link>
        <Link href="/inventory" className="flex flex-col items-center gap-1 text-slate-500">
          <MaterialIcon name="directions_car" className="text-2xl" />
          <span className="text-[10px] font-bold uppercase">Inventory</span>
        </Link>
        <Link href="/studio" className="relative -top-4">
          <div className="size-14 rounded-full bg-[#0dccf2] flex items-center justify-center shadow-lg shadow-[#0dccf2]/30 border-4 border-[#0a0f0f]">
            <MaterialIcon name="auto_awesome" className="text-[#0a0f0f] text-2xl" />
          </div>
        </Link>
        <Link href="/leads" className="flex flex-col items-center gap-1 text-slate-500">
          <MaterialIcon name="group" className="text-2xl" />
          <span className="text-[10px] font-bold uppercase">Leads</span>
        </Link>
        <Link href="/settings" className="flex flex-col items-center gap-1 text-slate-500">
          <MaterialIcon name="settings" className="text-2xl" />
          <span className="text-[10px] font-bold uppercase">Settings</span>
        </Link>
      </nav>
    </div>
  );
}
